# Generated by Django 6.0.3 on 2026-03-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0002_rename_date_created_ticket_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed',
        ),
    ]
