# Generated by Django 6.0.3 on 2026-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_remove_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
